version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
volumes:
  db-store:
