import './globals.css';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import { LogoutButton } from './LogoutButton';
import { LoginButton } from './LoginButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between p-4">
          <Link href="/">ホーム</Link>

          <div>
            <LoginButton />
            <LogoutButton />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
